### ISSUE TITLE
Автоматичне поновлення підписок

### ISSUE THREAD

**Issue by dimaischenko** [plakidan/monobank-pay#3]
Вітання! Не знайшов у API mono моно явних інструментів для автоматичних підписок (Auto-renewable Subscriptions). Може знаєте, чи це можливо в принципі? Може потрібна якась самостійна реалізація?

**Comment by plakidan** [comment]
> Вітання! Не знайшов у API mono моно явних інструментів для автоматичних підписок (Auto-renewable Subscriptions). Може знаєте, чи це можливо в принципі? Може потрібна якась самостійна реалізація?

ВІтаю. Наразі у моно такого функціоналу немає

Зараз я випущу нову версію API із токенами карт, і напишу як це можна реалізувати самотужки

**Comment by dimaischenko** [comment]
> Зараз я випущу нову версію API із токенами карт, і напишу як це можна реалізувати самотужки

Офігенно! Дякую! Я планую на python все робити, та буде зрозуміло, що до чого.

**Comment by plakidan** [comment]
@dimaischenko 
Все дуже просто робиться у кілька кроків:

1. Створюємо посилання на оплату зі збереженням токену картки клієнта
2. Ловимо вебхук і зберігаємо токен клієнта
3. Також у вас має десь берегтись список активних підписок
4. Далі по CRON або через іншого планувальника запускажте функцію яка перевірить усі підписки і ті що завершуються - спробувати зняти кошти і продлити підписку

**Comment by dimaischenko** [comment]
> 4. Далі по CRON або через іншого планувальника запускажте функцію яка перевірить усі підписки і ті що завершуються - спробувати зняти кошти і продлити підписку

Звучить логічно. Тільки от хіба Mono не повинні якось зі свого боку це контролювати? Адже насправді виходить, що я можу зняти скільки завгодно коштів, як захочу. Умовно, людина підписалася на щомісячну, а я беру і знімаю в неї гроші щодня?

**Comment by plakidan** [comment]
> > 4. Далі по CRON або через іншого планувальника запускажте функцію яка перевірить усі підписки і ті що завершуються - спробувати зняти кошти і продлити підписку
> 
> Звучить логічно. Тільки от хіба Mono не повинні якось зі свого боку це контролювати? Адже насправді виходить, що я можу зняти скільки завгодно коштів, як захочу. Умовно, людина підписалася на щомісячну, а я беру і знімаю в неї гроші щодня?

Все вірно. Ви можете знімати скільки хочете. Банк надає вам послуги еквайрінгу, просто, зручно, і прозоро. 
Далі реалізація всієї логіки у ваших руках

**Comment by dimaischenko** [comment]
Дякую! Розбиратимуся. Просто у клієнта ж повинна виникати довіра і впевненість у покупці або підписці, що все буде як зазначено, і в мене було розуміння, що моно теж це гарантує своїм еквайрінгом і дає таку впевненість. Піду читати теорію, дякую!
