### ISSUE TITLE
где качать composer require plakidan/monobank-pay

### ISSUE THREAD

**Issue by WebOrman** [plakidan/monobank-pay#4]
где качать composer require plakidan/monobank-pay ?

откуда брать require_once 'vendor/autoload.php'; ?

можно подробнее плиз

**Comment by plakidan** [comment]
> где качать composer require plakidan/monobank-pay ?
> 
> откуда брать require_once 'vendor/autoload.php'; ?
> 
> можно подробнее плиз

Чи знаєте ви що таке composer? Користуєтесь ним?

**Comment by plakidan** [comment]
@WebOrman якщо не має змоги використати composer, напишіть мені, підкажу як обійтись без нього

**Comment by andrew-demb** [comment]
https://getcomposer.org/doc/00-intro.md

**Comment by plakidan** [comment]
@WebOrman Раджу ознайомитись:

http://weblib.com.ua/blog/znayomstvo-z-composer-menedzherom-zalezhnostey-php

**Comment by WebOrman** [comment]
> @WebOrman якщо не має змоги використати composer, напишіть мені, підкажу як обійтись без нього

шобы я понимал как здесь написать в личку ))  я так понимаю что 2 ссылки выше это по этому вопросу. одна с для скачать композер, другая чтобы понять как без него. _____ офтоп - как связаться за сотрудничество?

**Comment by plakidan** [comment]
Чи використовуєте ви якийсь фреймворк? 
Яка у вас ціль використання бібліотеки?

**Comment by WebOrman** [comment]
@plakidan это все же две ссылки для композера )) таки расскажите как без него обойтись?? оплата привата как то проще настраивается. тупо кнопку формой со всеми пост переменными сделал и все. в моно что то они решили намутить, шобы жизнь медом не казалась ))

**Comment by WebOrman** [comment]
> Чи використовуєте ви якийсь фреймворк? Яка у вас ціль використання бібліотеки?

нет. самописный сайт на пхп. цель - сделать оплату на сайте через моно

**Comment by plakidan** [comment]
У привата ви мабуть маєте на увазі платіжний віджет, у моно такого немає

**Comment by WebOrman** [comment]
> У привата ви мабуть маєте на увазі платіжний віджет, у моно такого немає

именно. там наскока помню 3 варианта чтобы добавит оплату. у моно уже заметил что виджета нема )

**Comment by plakidan** [comment]
Тоді [завантажте останній  реліз ](https://github.com/plakidan/monobank-pay/archive/refs/tags/v0.2.0.zip)
Із архіву з релізом вам треба папка src, перейменовуєте її у зручну для вас назву, поміщаєте в десь у ваш проект, далі потрібно зробити 
```php
require_once base_path().'/path/to/src/Client.php';
require_once base_path().'/path/to/src/Payment.php';
require_once base_path().'/path/to/src/RequestBuilder.php';
```

також якщо треба ще вебхуки отримувати, то усього переліченого вище додайте

```php
require_once base_path().'/path/to/src/Webhook.php';
```

і після цього вже використвуйте класи для створення посилання на оплату

> P.S.
> base_path() - це для прикладу, функція я повертає шлях від корню до папки із вашим сайтом
> /path/to/src - шлях до папки із кодом який ви взяли із архіву з папки src

**Comment by WebOrman** [comment]
ок. спс . шас попробую разобраться ))
